services:
  db:
    image: postgres
    ports:
      - 127.0.0.1:5433:5432
    restart: unless-stopped
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_dev
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/user_dev
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  pg_data:
